"use strict";
// Generated by https://quicktype.io
Object.defineProperty(exports, "__esModule", { value: true });
exports.WindDir = exports.Text = exports.Icon = void 0;
var Icon;
(function (Icon) {
    Icon["CDNWeatherapiCOMWeather64X64Day113PNG"] = "//cdn.weatherapi.com/weather/64x64/day/113.png";
    Icon["CDNWeatherapiCOMWeather64X64Day116PNG"] = "//cdn.weatherapi.com/weather/64x64/day/116.png";
    Icon["CDNWeatherapiCOMWeather64X64Day119PNG"] = "//cdn.weatherapi.com/weather/64x64/day/119.png";
    Icon["CDNWeatherapiCOMWeather64X64Night113PNG"] = "//cdn.weatherapi.com/weather/64x64/night/113.png";
    Icon["CDNWeatherapiCOMWeather64X64Night116PNG"] = "//cdn.weatherapi.com/weather/64x64/night/116.png";
    Icon["CDNWeatherapiCOMWeather64X64Night119PNG"] = "//cdn.weatherapi.com/weather/64x64/night/119.png";
})(Icon || (exports.Icon = Icon = {}));
var Text;
(function (Text) {
    Text["Clear"] = "Clear";
    Text["Cloudy"] = "Cloudy";
    Text["PartlyCloudy"] = "Partly cloudy";
    Text["Sunny"] = "Sunny";
})(Text || (exports.Text = Text = {}));
var WindDir;
(function (WindDir) {
    WindDir["S"] = "S";
    WindDir["Ssw"] = "SSW";
    WindDir["Sw"] = "SW";
    WindDir["W"] = "W";
    WindDir["Wnw"] = "WNW";
    WindDir["Wsw"] = "WSW";
})(WindDir || (exports.WindDir = WindDir = {}));
